<?php

/**
 * Implements hook_ctools_plugin_directory().
 * Contains a single hook based on MYMODULE_ctools_plugin_directory, 
 * which lets us tell Feed Tamper (via CTools) where our plugins are going to be. 
 * In this case they will be in a sub-folder of the module, brahms_xml_feeds/plugins.
 */
function solanaceae_feeds_tamper_ctools_plugin_directory($module, $plugin){
  if($module === 'feeds_tamper'){
    return 'plugins';
  }
}
